spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_shop?useSSL=false
    username: root
    password: pass
  jpa:
    show-sql: true
server:
  port: 8189
  servlet:
    context-path: /shop
logging:
  level:
    root: info
    org:
      springframework:
        web: debug
        hibernate: error
        data: error
  file:
    path: logs
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'


